est=('pri','ver','inve','out')
alunos=['raf','pedro','bianca','jessica','bruno']
print(est[0])
print(est[1])
print(alunos[2])
print(alunos[4])
alunos[0]='carlos'
print(alunos)
alunos.append('helena')
print(alunos)
print(alunos[5])
